-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS repository.tbl_batches
(
    id serial NOT NULL,
    region character varying(50) COLLATE pg_catalog."default",
    company character varying(50) COLLATE pg_catalog."default",
    workflow character varying(50) COLLATE pg_catalog."default",
    filename character varying(250) COLLATE pg_catalog."default",
    location character varying(255) COLLATE pg_catalog."default",
    filetype character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    createddate timestamp without time zone,
    statusdate timestamp without time zone,
    comment text COLLATE pg_catalog."default",
    data bytea,
    archived boolean,
    CONSTRAINT tbl_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS repository.tbl_certificates
(
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(100) COLLATE pg_catalog."default",
    data bytea,
    CONSTRAINT tbl_certificates_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS repository.tbl_companies
(
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    odbcdsn character varying(50) COLLATE pg_catalog."default",
    server character varying(50) COLLATE pg_catalog."default",
    port integer,
    database character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tbl_companies_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS repository.tbl_globals
(
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    value character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tbl_globals_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS repository.tbl_regions
(
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    receiverid character varying(50) COLLATE pg_catalog."default",
    receivername character varying(50) COLLATE pg_catalog."default",
    receivercode character varying(50) COLLATE pg_catalog."default",
    submitterid character varying(50) COLLATE pg_catalog."default",
    submittername character varying(50) COLLATE pg_catalog."default",
    submitternumber character varying(50) COLLATE pg_catalog."default",
    submittercontact character varying(50) COLLATE pg_catalog."default",
    submitterphone character varying(50) COLLATE pg_catalog."default",
    submitteraddress1 character varying(50) COLLATE pg_catalog."default",
    submitteraddress2 character varying(50) COLLATE pg_catalog."default",
    submittercity character varying(50) COLLATE pg_catalog."default",
    submitterstate character varying(50) COLLATE pg_catalog."default",
    submitterzip character varying(50) COLLATE pg_catalog."default",
    production boolean,
    login character varying(50) COLLATE pg_catalog."default",
    password character varying(50) COLLATE pg_catalog."default",
    phone character varying(250) COLLATE pg_catalog."default",
    zipability boolean,
    updateallowable boolean,
    postzeropay boolean,
    uploadmask character varying(255) COLLATE pg_catalog."default",
    downloadmask character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tbl_regions_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS repository.tbl_variables
(
    name character varying(31) COLLATE pg_catalog."default" NOT NULL,
    value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tbl_variables_pkey PRIMARY KEY (name)
);
END;