"""Create inventory management tables

Revision ID: e53f63499ba7
Revises: d38eb9f8adb2
Create Date: 2024-12-14 17:52:31.098902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53f63499ba7'
down_revision: Union[str, None] = 'd38eb9f8adb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
